---
- hosts: ELK-E
  remote_user: root
  tasks:
    - name: install the latest version of Java,and Elasticsearch
      yum:
        name: java-1.8.0-openjdk,elasticsearch
        state: latest
      notify: restart elasticsearch
    - name: Copy file with owner and permissions
      copy:
        src: elk/hosts
        dest: /etc/hosts
        owner: root
        group: root
        mode: '0644'  
    - template:
        src: elk/elasticsearch.yml
        dest: /etc/elasticsearch/elasticsearch.yml
        owner: root
        group: root
        mode: '0644'  
      notify: restart elasticsearch
  handlers:
    - name: restart elasticsearch
      service:
        name: elasticsearch
        state: restarted
        enabled: yes
#使用(curl 192.168.1.203:9200/_cluster/health?pretty)验证

#########################################################################
- hosts: ELK-K
  remote_user: root
  tasks: 
    - name: install the latest version of Kibana
      yum:
        name: kibana
        state: latest
    - name: Copy file with owner and permissions
      copy:
        src: elk/hosts
        dest: /etc/hosts
        owner: root
        group: root
        mode: '0644'
    - copy:
        src: elk/kibana.yml
        dest: /opt/kibana/config/kibana.yml
        owner: root
        group: root
        mode: '0644'
      notify: restart kibana
  handlers:
    - name: restart kibana
      service:
        name: kibana
        state: restarted
        enabled: yes

#####################################################################
- hosts: ELK-L
  remote_user: root
  tasks:
    - name: install the latest version of Logstash
      yum:
        name: java-1.8.0-openjdk,logstash
        state: latest

